/*
	notes
		- this is a react component
      - note capital letter first
      - redux use camel case
*/



import React, { useEffect, useMemo } from 'react'
import { useDispatch } from 'react-redux'



import { useSelector } from 'react-redux'
/*
	- useSelector
		- React components can read data from the Redux store using the useSelector hook from the React-Redux library
*/



import { selectAllPosts, fetchPosts, selectPostIds, selectPostById } from './postsSlice'
/*
  - selectAllPosts
    - import selectAllPosts in slice for reuse
  - fetchPosts
    - this is a thunk created in createAsyncThunk in postsSlice
    - thunks are created using createAsyncThunk
      - createAsyncThunk
        - Redux Toolkit's createAsyncThunk API generates thunks that automatically dispatch those "start/success/failure" actions for you
        - you can now use this to call async requests        
*/



import { Link } from 'react-router-dom'
import classnames from 'classnames'



import { PostAuthor } from './PostAuthor'
import { TimeAgo } from './TimeAgo'
import { ReactionButtons } from './ReactionButtons'
import { Spinner } from '../../components/Spinner'
/*
  - PostAuthor, TimeAgo, ReactionButtons, Spinner
    - these are just react components
*/



import { useGetPostsQuery } from '../api/apiSlice'
/*
  - useGetPostsQuery
    - auto generated by apiSlice when using createApi()
*/







const PostExcerpt = ({ post }) => {
  // const post = useSelector(state => selectPostById(state, postId)) not using this in rtk query
  return (
    <article className="post-excerpt" key={post.id}>
      <h3>{post.title}</h3>
      <div>
        <PostAuthor userId={post.user} />
        <TimeAgo timestamp={post.date} />
      </div>
      <p className="post-content">{post.content.substring(0, 100)}</p>

      <ReactionButtons post={post} />
      <Link to={`/posts/${post.id}`} className="button muted-button">
        View Post
      </Link>
    </article>
  )
}






export const PostsList = () => {
  /*
  it seems we dont need these in rtk query
  const dispatch = useDispatch()
  const orderedPostIds = useSelector(selectPostIds)
  */
  const {
    data: posts = [],
    /*
      - posts
        - data is renamed to posts so it can be easily recognized and use below
        - give posts a default empty array in case it's undefined, so that we always have an array to sort on
        - sorting
          - We can't just call posts.sort() directly, because Array.sort() mutates the existing array, 
          - so we'll need to make a copy of it first. 
            - To avoid re-sorting on every rerender, we can do the sorting in a useMemo() hook
    */
    isLoading,
    isFetching,
    isSuccess,
    isError,
    error,
    refetch
  } = useGetPostsQuery()
  /*
    - rtk query notes
      - Each generated query hook returns a "result" object containing several fields
      - data
        - the actual response contents from the server. This field will be undefined until the response is received.
      - isLoading
        - a boolean indicating if this hook is currently making the first request to the server
      - isFetching
        - a boolean indicating if the hook is currently making any request to the server
      - isSuccess
        - a boolean indicating if the hook has made a successful request and has cached data available
      - isError
        - a boolean indicating if the last request had an error
      - error
        - a serialized error object
  */


/*
  const posts = useSelector(state => state.posts)
	- useSelector
		- Our initial PostsList component will read the state.posts value from the Redux store
			- then loop over the array of posts and show each of them on screen
*/  
//  const posts = useSelector(selectAllPosts) not needed in rtk query
/*
  - selectAllPosts
    - use selectAllPosts for reuse
*/



  /*
  not needed in rtk query
  const postStatus = useSelector(state => state.posts.status)
  const error = useSelector(state => state.posts.error)
  */



  /*
  not needed in rtk query
  useEffect(() => {
    if (postStatus === 'idle') {
      dispatch(fetchPosts())
    }
  }, [postStatus, dispatch])
    - useEffect
      - after component render, trigger arrow function
      - call dispatch(fetchPosts()) if postStatus is idle
      - trigger useEffect again if [postStatus, dispatch] changed
  */



  const sortedPosts = useMemo(() => {
    const sortedPosts = posts.slice()
    // Sort posts in descending chronological order
    sortedPosts.sort((a, b) => b.date.localeCompare(a.date))
    return sortedPosts
  }, [posts])
  /*
  - useMemo - sorting
    - We can't just call posts.sort() directly, because Array.sort() mutates the existing array, 
    - so we'll need to make a copy of it first. 
      - To avoid re-sorting on every rerender, we can do the sorting in a useMemo() hook
  */  



  let content

  if (isLoading) {
    content = <Spinner text="Loading..." />
  } else if (isSuccess) {


    /*
    not needed in rtk query
    // Sort posts in reverse chronological order by datetime string
    const orderedPosts = posts
      .slice()
      .sort((a, b) => b.date.localeCompare(a.date))*/

    /*content = orderedPosts.map(post => (
      <PostExcerpt key={post.id} post={post} />
    ))*/
    /*
    not needed in rtk query
    content = orderedPostIds.map(postId => (        // we started using this when we setup createEntityAdapter in slice
      <PostExcerpt key={postId} postId={postId} />
    ))*/

    const renderedPosts = sortedPosts.map(post => (
      <PostExcerpt key={post.id} post={post} />
    ))
    const containerClassname = classnames('posts-container', {
      disabled: isFetching
    })
    content = <div className={containerClassname}>{renderedPosts}</div>
  } else if (isError) {
    content = <div>{error.toString()}</div>
  }


  return (
    <section className="posts-list">
      <h2>Posts</h2>
      <button onClick={refetch}>Refetch Posts</button>
      {content}
    </section>
  )


} /*close braket export const PostsList */